[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pixel-code"
version = "0.5.1"
description = "TUI - Project organization tool"
authors = [{name = "OrAxelerator"}]
license = { file = "LICENSE.md" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "platformdirs",
    "requests",
    "windows-curses; platform_system == 'Windows'"
]
keywords = ["tui", "cli", "productivity", "project-manager"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers"
]

[project.scripts]
pixel-code = "pixel_code.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pixel_code*"]

[tool.setuptools.package-data]
pixel_code = ["data/*.txt"]

[project.urls]
Homepage = "https://github.com/OrAxelerator/Pixel_Code"
Repository = "https://github.com/OrAxelerator/Pixel_Code"
Issues = "https://github.com/OrAxelerator/Pixel_Code/issues"
